# Generated by Django 4.2.3 on 2023-08-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advetisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
